# Generated by Django 2.2.7 on 2019-11-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='name_of_state',
            new_name='title',
        ),
    ]
